# Generated by Django 3.2.9 on 2021-11-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0002_alter_operador_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operador',
            old_name='user_operador',
            new_name='username',
        ),
    ]
